import type { PantryItem, Recipe, ShoppingItem } from './types';

const ingredient = (
  id: string,
  name: string,
  amount: number,
  unit: Recipe['ingredients'][number]['unit'],
  category: Recipe['ingredients'][number]['category'],
  optional = false,
) => ({ id, name, amount, unit, category, optional });

export const starterRecipes: Recipe[] = [
  {
    id: 'recipe-pasta',
    title: 'Creamy lemon pasta',
    description: 'A bright, silky pasta for a weeknight when you want dinner fast.',
    minutes: 20,
    servings: 2,
    category: 'Quick dinner',
    tags: ['Vegetarian', '20 min'],
    accent: 'apricot',
    icon: '🍋',
    favorite: true,
    ingredients: [
      ingredient('pasta', 'Spaghetti', 200, 'g', 'Dry goods'),
      ingredient('courgette', 'Courgette', 1, 'pcs', 'Produce'),
      ingredient('garlic', 'Garlic', 2, 'pcs', 'Produce'),
      ingredient('lemon', 'Lemon', 1, 'pcs', 'Produce'),
      ingredient('cream', 'Cooking cream', 200, 'ml', 'Dairy'),
      ingredient('parmesan', 'Parmesan', 50, 'g', 'Dairy'),
      ingredient('oil', 'Olive oil', 15, 'ml', 'Other'),
      ingredient('salt', 'Salt', 5, 'g', 'Seasoning'),
    ],
    steps: [
      'Cook the spaghetti in salted water until just tender. Reserve 100 ml of the cooking water.',
      'Fry the sliced courgette and garlic in olive oil until soft and lightly golden.',
      'Stir in the cream, lemon zest, and half the parmesan. Loosen with cooking water.',
      'Toss with the pasta, finish with lemon juice, and serve with the remaining parmesan.',
    ],
    createdAt: '2026-09-24T10:00:00.000Z',
  },
  {
    id: 'recipe-stew',
    title: 'Tomato lentil stew',
    description: 'A one-pot bowl with enough depth for lunch tomorrow, too.',
    minutes: 35,
    servings: 4,
    category: 'One pot',
    tags: ['Vegan', 'Batch cook'],
    accent: 'tomato',
    icon: '🍅',
    favorite: false,
    ingredients: [
      ingredient('lentils', 'Red lentils', 250, 'g', 'Dry goods'),
      ingredient('tomatoes', 'Chopped tomatoes', 400, 'g', 'Dry goods'),
      ingredient('onion', 'Yellow onion', 1, 'pcs', 'Produce'),
      ingredient('carrot', 'Carrot', 2, 'pcs', 'Produce'),
      ingredient('stock', 'Vegetable stock', 600, 'ml', 'Other'),
      ingredient('cumin', 'Ground cumin', 3, 'g', 'Seasoning'),
      ingredient('spinach', 'Baby spinach', 100, 'g', 'Produce', true),
    ],
    steps: [
      'Cook the onion and carrot with cumin until the onion is translucent.',
      'Add lentils, tomatoes, and stock. Bring to a simmer.',
      'Cook for 25 minutes, stirring once or twice, until the lentils are tender.',
      'Fold in spinach if using. Season to taste and serve with bread or rice.',
    ],
    createdAt: '2026-09-21T10:00:00.000Z',
  },
  {
    id: 'recipe-wraps',
    title: 'Crispy chickpea wraps',
    description: 'Crunchy chickpeas, cool yoghurt, and fresh vegetables in a warm wrap.',
    minutes: 25,
    servings: 2,
    category: 'Fast lunch',
    tags: ['Vegetarian', 'High fibre'],
    accent: 'sage',
    icon: '🥙',
    favorite: false,
    ingredients: [
      ingredient('chickpeas', 'Chickpeas', 240, 'g', 'Protein'),
      ingredient('flatbread', 'Flatbread', 2, 'pcs', 'Dry goods'),
      ingredient('cucumber', 'Cucumber', 1, 'pcs', 'Produce'),
      ingredient('yoghurt', 'Greek yoghurt', 150, 'g', 'Dairy'),
      ingredient('red-onion', 'Red onion', 0.5, 'pcs', 'Produce'),
      ingredient('lemon-wrap', 'Lemon', 0.5, 'pcs', 'Produce'),
      ingredient('paprika', 'Smoked paprika', 3, 'g', 'Seasoning'),
    ],
    steps: [
      'Drain the chickpeas, then toss them with oil, smoked paprika, and a pinch of salt.',
      'Roast or pan-fry until crisp at the edges.',
      'Mix yoghurt with lemon juice and a little salt. Slice the cucumber and onion.',
      'Warm the flatbreads, then fill with yoghurt, vegetables, and chickpeas.',
    ],
    createdAt: '2026-09-18T10:00:00.000Z',
  },
  {
    id: 'recipe-salmon',
    title: 'Miso salmon tray',
    description: 'Salmon and greens on one tray with a savoury-sweet glaze.',
    minutes: 30,
    servings: 2,
    category: 'Dinner',
    tags: ['Pescatarian', 'One tray'],
    accent: 'sky',
    icon: '🐟',
    favorite: true,
    ingredients: [
      ingredient('salmon', 'Salmon fillets', 2, 'pcs', 'Protein'),
      ingredient('potato', 'Baby potatoes', 500, 'g', 'Produce'),
      ingredient('broccoli', 'Broccoli', 300, 'g', 'Produce'),
      ingredient('miso', 'Miso paste', 2, 'tbsp', 'Other'),
      ingredient('honey', 'Honey', 1, 'tbsp', 'Other'),
      ingredient('sesame', 'Sesame seeds', 1, 'tbsp', 'Other', true),
    ],
    steps: [
      'Heat the oven to 210°C. Roast the halved potatoes with oil for 18 minutes.',
      'Mix miso, honey, and a splash of water into a glaze.',
      'Add broccoli and salmon to the tray. Brush the salmon with glaze.',
      'Roast for 10 to 12 minutes, then scatter with sesame seeds if using.',
    ],
    createdAt: '2026-09-12T10:00:00.000Z',
  },
];

export const starterPantry: PantryItem[] = [
  { id: 'pantry-spaghetti', name: 'Spaghetti', quantity: 500, unit: 'g', category: 'Dry goods', updatedAt: '2026-10-01T10:00:00.000Z' },
  { id: 'pantry-garlic', name: 'Garlic', quantity: 4, unit: 'pcs', category: 'Produce', updatedAt: '2026-10-01T10:00:00.000Z' },
  { id: 'pantry-oil', name: 'Olive oil', quantity: 500, unit: 'ml', category: 'Other', updatedAt: '2026-09-28T10:00:00.000Z' },
  { id: 'pantry-salt', name: 'Salt', quantity: 80, unit: 'g', category: 'Seasoning', updatedAt: '2026-09-28T10:00:00.000Z' },
  { id: 'pantry-lentils', name: 'Red lentils', quantity: 500, unit: 'g', category: 'Dry goods', updatedAt: '2026-09-27T10:00:00.000Z' },
  { id: 'pantry-tomatoes', name: 'Chopped tomatoes', quantity: 800, unit: 'g', category: 'Dry goods', updatedAt: '2026-09-27T10:00:00.000Z' },
  { id: 'pantry-onions', name: 'Yellow onion', quantity: 3, unit: 'pcs', category: 'Produce', updatedAt: '2026-10-02T10:00:00.000Z' },
  { id: 'pantry-carrots', name: 'Carrot', quantity: 5, unit: 'pcs', category: 'Produce', updatedAt: '2026-10-02T10:00:00.000Z' },
  { id: 'pantry-stock', name: 'Vegetable stock', quantity: 1000, unit: 'ml', category: 'Other', updatedAt: '2026-09-27T10:00:00.000Z' },
  { id: 'pantry-cumin', name: 'Ground cumin', quantity: 20, unit: 'g', category: 'Seasoning', updatedAt: '2026-09-27T10:00:00.000Z' },
  { id: 'pantry-chickpeas', name: 'Chickpeas', quantity: 240, unit: 'g', category: 'Protein', updatedAt: '2026-09-25T10:00:00.000Z' },
  { id: 'pantry-cucumber', name: 'Cucumber', quantity: 1, unit: 'pcs', category: 'Produce', updatedAt: '2026-10-02T10:00:00.000Z', expiresAt: '2026-10-06' },
  { id: 'pantry-yoghurt', name: 'Greek yoghurt', quantity: 500, unit: 'g', category: 'Dairy', updatedAt: '2026-10-02T10:00:00.000Z', expiresAt: '2026-10-08' },
  { id: 'pantry-paprika', name: 'Smoked paprika', quantity: 30, unit: 'g', category: 'Seasoning', updatedAt: '2026-09-25T10:00:00.000Z' },
];

export const starterShopping: ShoppingItem[] = [
  { id: 'shopping-coffee', name: 'Coffee beans', amount: 250, unit: 'g', category: 'Other', checked: false, sourceRecipeIds: [] },
  { id: 'shopping-bananas', name: 'Bananas', amount: 4, unit: 'pcs', category: 'Produce', checked: true, sourceRecipeIds: [] },
];
